<?php

namespace app\controller;

class Code
{
    const FAILED = 0;
    const DONE = 1;
    const INPUT_ERROR = -1;
    const TOKEN_ERROR = -2;
    const REQUEST_ERROR = -3;
    const SESSION_ERROR = -4;
    const DATA_REMOVED = -5;
    const DATA_LOCKED = -6;
    const DATA_NONE = -7;
    const DATABASE_ERROR = -8;
    const SYSTEM_ERROR = -9;
    const RIGHT_ERROR = -10;
    const EMAIL_SERVICE_ERROR = -11;
    const MOBILE_PHONE_SERVICE_ERROR = -12;

    const USER_RIGHT_CODE_ARTICLE = 'ARTICLE';
    const USER_RIGHT_CODE_CATEGORY = 'CATEGORY';

    const USERNAME_REQUIRE = 10001;
    const USERNAME_LENGTH = 10010;
    const USERNAME_FORMAT = 10100;
    const USERNAME_MISMATCH = 11000;

    const PASSWORD_REQUIRE = 20001;
    const PASSWORD_LENGTH = 20010;
    const PASSWORD_FORMAT = 20100;
    const PASSWORD_MISMATCH = 21000;

    const CAPTCHA_REQUIRE = 50001;
    const CAPTCHA_LENGTH = 50010;
    const CAPTCHA_FORMAT = 50100;
    const CAPTCHA_MISMATCH = 51000;

    const METHOD_REQUIRE = 60001;
    const METHOD_LENGTH = 60010;
    const METHOD_FORMAT = 60100;
    const METHOD_MISMATCH = 61000;

    const EMAIL_ADDRESS_REQUIRE = 70001;
    const EMAIL_ADDRESS_FORMAT = 70100;
    const EMAIL_ADDRESS_MISMATCH = 71000;

    const MOBILE_PHONE_NUMBER_REQUIRE = 80001;
    const MOBILE_PHONE_NUMBER_FORMAT = 80100;
    const MOBILE_PHONE_NUMBER_MISMATCH = 81000;

    const SMS_VERIFICATION_CODE_REQUIRE = 90001;
    const SMS_VERIFICATION_CODE_LENGTH = 90010;
    const SMS_VERIFICATION_CODE_FORMAT = 90100;
    const SMS_VERIFICATION_CODE_MISMATCH = 91000;

    const UPLOAD_FILE_ILLEGAL = 100001;
    const UPLOAD_FILE_SIZE_LIMIT = 100010;
    const UPLOAD_FILE_EXTENSION_LIMIT = 100100;
    const UPLOAD_FILE_MIME_TYPE_LIMIT = 101000;

    const METHOD_EMAIL = 1;
    const METHOD_MOBILE_PHONE = 2;

    const SCENE_RESET_PASSWORD_BY_EMAIL = 27;
    const SCENE_RESET_PASSWORD_BY_MOBILE_PHONE = 28;

    const ARTICLE_AUTHOR_TYPE_CREATOR = 0;
}
